- backend/src/config/constants.js
- frontend/components/Article.js
- frontend/components/CourseEditor.js
- frontend/components/Hero.js
- frontend/components/MediaGallery.js
- frontend/components/MediaManager.js
- frontend/components/MediaManagerDialog.js
- frontend/components/MediaSelector.js
- frontend/components/SiteSettings.js
- frontend/components/TextEditor/Editor.js
- frontend/components/TextEditor/EditorUI.js
- frontend/components/TextEditor/MediaRenderer.js
- frontend/config/constants.js
- frontend/pages/create.js
- frontend/pages/index.js
Fixed:
- Editor:
- Using images
- Bottom toolbar
- UI improvements like padding etc.
- UI improvements
- Images in the articles
> Editing fixes: using media, bottom toolbar and other UI improvements

- deployment/install.yml
- deployment/roles/common/tasks/main.yml
- docs/README.md
Also includes a fix for non renewing SSL certs.
> Debian 10 Buster compatible Ansible script

- deployment/install.yml
- deployment/roles/install_softwares/tasks/main.yml
- deployment/roles/letsencrypt/tasks/main.yml
- deployment/roles/setup_docker/tasks/main.yml
- deployment/templates/.env.j2
- deployment/templates/.env.ssl.j2
- The deployment script does not ask for settings right at the start of the script.
- The script has been broken down into more roles.
> More streamlined deployment

- deployment/docker/docker-compose.yml
- deployment/install.sh
Users can install CourseLit without Ansible now.
> BASH Installer Script

- packages/api/src/graphql/courses/logic.js
- packages/api/src/payments/stripe_payment.js
- packages/api/src/routes/payment.js
- packages/app/components/CheckoutExternal/Free.js
- packages/app/components/CheckoutExternal/index.js
- packages/app/components/Public/Article.js
- packages/app/components/Public/BaseLayout/ComponentScaffold.js
- packages/app/components/Public/BaseLayout/DrawerListItemIcon.js
- packages/app/config/strings.js
- packages/app/package.json
- yarn.lock
This commit includes
- New enroll button for free courses.
- Drawer opens automatically on mobile on `/course` routes.
> Course area enhancements

- .github/workflows/publish-docker-images.yaml
- .github/workflows/publish-packages.yaml
- Broken the workflow into two parts i.e. publishing packages and publishing Docker images
- Tagging Docker images
> Changed the workflow

- apps/web/middlewares/verify-domain.ts
- packages/state-management/src/store.ts
> Fixed a bug: 200

- apps/web/components/admin/design/themes-manager/index.tsx
- apps/web/components/admin/design/themes-manager/theme-item.tsx
- apps/web/components/admin/settings.tsx
- apps/web/components/public/code-injector.tsx
- apps/web/graphql/design/logic.ts
- apps/web/graphql/settings/types.ts
- apps/web/models/Customisation.js
- apps/web/models/SiteInfo.ts
- apps/web/pages/_app.tsx
- apps/web/ui-config/strings.ts
- apps/web/ui-models/site-info.ts
- packages/common-models/src/site-info.ts
- packages/state-management/src/action-creators.ts
- packages/state-management/src/default-state.ts
- packages/state-management/src/reducer.ts
In this PR
**New**
- Code injection in the `<body>` tag.
**Refactoring**
- Themes
- Code injection in the `<head>` tag.
> Refactored themes and customisation

- apps/web/graphql/pages/logic.ts
- apps/web/graphql/users/logic.ts
- apps/web/lib/passport-magic-link.ts
> Mandatory pages are created upon admin signup

- apps/web/.env
- apps/web/config/constants.ts
- apps/web/config/strings.ts
- apps/web/graphql/mails/logic.ts
- apps/web/services/mail.ts
- deployment/docker/docker-compose.yml
Queue will be used only when an environment variable `QUEUE_SERVER` is set. Example value: `http://queue`.
> Queue as progressive enhancement

- apps/web/graphql/pages/logic.ts
- apps/web/graphql/pages/page-templates.ts
- packages/common-widgets/src/faq/index.ts
- packages/common-widgets/src/pricing/index.ts
- packages/components-library/src/styles.css
> Default home page template

- apps/web/graphql/lessons/helpers.ts
- apps/web/graphql/lessons/logic.ts
- apps/web/graphql/lessons/types.ts
- apps/web/models/Lesson.ts
- apps/web/pages/course/[slug]/[id]/index.tsx
- packages/common-widgets/src/content/widget.tsx
> Removed groupRank

- packages/common-widgets/src/header/defaults.ts
> Fixed header login button

- apps/web/components/admin/settings/index.tsx
- packages/components-library/src/form-field.tsx
> Fixed mailing address

- apps/web/pages/course/[slug]/[id]/index.tsx
> Fixed profile and lock visibility

- apps/web/components/public/lesson-viewer/index.tsx
- packages/components-library/src/text-renderer.tsx
> Fixed lock visibility in the lesson viewer

- apps/web/components/public/article.tsx
- apps/web/components/public/checkout/free.tsx
- apps/web/components/public/checkout/stripe.tsx
- apps/web/components/public/lesson-viewer/index.tsx
- apps/web/pages/course/[slug]/[id]/index.tsx
- apps/web/pages/my-content.tsx
- apps/web/pages/profile/index.tsx
- packages/common-widgets/src/banner/widget.tsx
- packages/common-widgets/src/header/widget/mobile-nav.tsx
- packages/components-library/src/drawer.tsx
> Replaced Button with Button2 in public pages

- packages/common-widgets/src/pricing/widget.tsx
> Fixed the UI

- apps/web/components/public/base-layout/index.tsx
- apps/web/pages/blog/[slug]/[id].tsx
> Twitter cards for blog posts

- packages/common-widgets/src/featured/widget.tsx
> Skeleton for Featured widget

- apps/web/components/admin/products/editor/content/lesson.tsx
- apps/web/graphql/activities/logic.ts
> Fixed lifetime filter

- apps/web/components/admin/users/index.tsx
- apps/web/components/public/article.tsx
- apps/web/graphql/users/logic.ts
- apps/web/graphql/users/types.ts
- apps/web/models/User.ts
- apps/web/pages/profile/index.tsx
- apps/web/ui-models/profile.ts
- apps/web/ui-models/user.ts
- packages/common-models/src/profile.ts
- packages/common-models/src/user.ts
- packages/state-management/src/action-creators.ts
- packages/state-management/src/default-state.ts
- packages/state-management/src/reducer.ts
> Uploaded photo to user's profile

- apps/web/auth.ts
- apps/web/graphql/mails/logic.ts
- apps/web/pages/api/auth/code/generate.ts
> Bug: case sensitive emails

- apps/web/auth.ts
- apps/web/components/admin/users/details.tsx
- apps/web/graphql/users/logic.ts
- apps/web/graphql/users/query.ts
- apps/web/graphql/users/types.ts
- Users cannot edit their own permissions and active properties
- Users with `active: false` setting, cannot log in
- Re-written getUsers
> Fixed permission issues
